name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  install-prereqs:
    runs-on: windows-latest
    steps:
      - run: ${{ github.workspace }}/.github/workflows/prereqs/install-prereqs.ps1

#  build-module:
#      runs-on: windows-latest
#      strategy:
#        matrix:
#          pwsh-version: ['7.3.12', '7.2.23']
#      steps:
#        - uses: actions/checkout@v4
#        - name: Setup PowerShell
#          uses: microsoft/setup-powershell@v1
#          with:
#            pwsh-version: '7.3.12'

