name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: .\install-prereqs.ps1 -Force
        shell: powershell

      - run: echo 'C:\Program Files\Citrix\PowerShellModules' >> $env:GITHUB_PATH
        shell: powershell

      - run: .\test