name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  install-prereqs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: ${{ github.workspace }}/install-prereqs.ps1
        shell: powershell

      - run: echo 'C:\Program Files\Citrix\PowerShellModules' >> $env:GITHUB_PATH
        shell: powershell

  test:
    runs-on: windows-latest
    needs: install-prereqs
    steps:
      - uses: actions/checkoutv4

      - run: echo $env:PATH