name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: .\install-prereqs.ps1 -Force
        shell: powershell

      - run: |
          $env:PSModulePath += ";C:\Program Files\Citrix\PowerShellModules"
          echo $env:PSModulePath
          Get-Module -ListAvailable Citrix.*
        shell: powershell

      - run: |
          $env:PSModulePath += ";C:\Program Files\Citrix\PowerShellModules"
          .\test
        shell: powershell