name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  install-prereqs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: ${{ github.workspace }}/install-prereqs.ps1 -Verbose -Force
        shell: powershell

      - run: |
          $env:PSModulePath += ';C:\Program Files\Citrix\PowerShellModules'
          echo $env:PSModulePath
          get-module citrix* -ListAvailable
          Import-Module ${{github.workspace}}/module/CitrixAutodeploy/CitrixAutodeploy.psd1
          Initialize-CtxAutodeployEnv
        shell: powershell

#  build-module:
#      runs-on: windows-latest
#      strategy:
#        matrix:
#          pwsh-version: ['7.3.12', '7.2.23']
#      steps:
#        - uses: actions/checkout@v4
#        - name: Setup PowerShell
#          uses: microsoft/setup-powershell@v1
#          with:
#            pwsh-version: '7.3.12'

