name: CI

on:
  pull_request:

env:
  DEBUG: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: .\install-prereqs.ps1 -Force
        shell: powershell

      - run: |
          $env:PSModulePath += ";C:\Program Files\Citrix\PowerShellModules"
          .\test
        shell: powershell

      - name: Setup tmate session
        if: ${{ env.DEBUG }} == 'true'
        uses: mxschmitt/action-tmate@v3
